"""splent_feature_team

Revision ID: 3f76830b5164
Revises: 1bb39441d98d
Create Date: 2026-06-27 23:28:16.486569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f76830b5164'
down_revision = '1bb39441d98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member', sa.Column('links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_member', 'links')
    # ### end Alembic commands ###
